### ISSUE TITLE
Errors while generating image

### ISSUE THREAD

**Issue by SijmenHuizenga** [SijmenHuizenga/willekeurigecreaties#2]
Running in docker. Logs:
```
creating new ART
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>
Traceback (most recent call last):
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>
  File "/usr/local/lib/python3.8/threading.py", line 1373, in _shutdown
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 1373, in _shutdown
  File "/usr/local/lib/python3.8/threading.py", line 1373, in _shutdown
  File "/usr/local/lib/python3.8/threading.py", line 1373, in _shutdown
    assert tlock.locked()
    assert tlock.locked()
    assert tlock.locked()
    assert tlock.locked()
AssertionError: 
AssertionError: 
AssertionError: 
AssertionError: 
ART completed 1606226217.jpg
```

**Comment by SijmenHuizenga** [comment]
Fixed
